// AetherJS v0.2 模板渲染产物(规格 16)—— 由白名单文法 IR 重建,禁止手改
// 数据约定:根变量 it;挂载走 IR→DOM 或 DOMParser 复检(16.4),innerHTML 不经手
export default function (AETHER, it) {
  var $get = AETHER.get, $set = AETHER.set, $obj = AETHER.obj;
  var $call = AETHER.call, $mcall = AETHER.mcall, $iter = AETHER.iter;
  var $test = AETHER.test, $bool = AETHER.bool, $not = AETHER.not;
  var $add = AETHER.add, $sub = AETHER.sub, $mul = AETHER.mul, $div = AETHER.div, $mod = AETHER.mod, $pow = AETHER.pow;
  var $band = AETHER.band, $bor = AETHER.bor, $bxor = AETHER.bxor, $bnot = AETHER.bnot;
  var $shl = AETHER.shl, $shr = AETHER.shr, $shru = AETHER.shru, $neg = AETHER.neg;
  var $lt = AETHER.lt, $le = AETHER.le, $gt = AETHER.gt, $ge = AETHER.ge;
  var $esc = AETHER.escText, $escA = AETHER.escAttr, $url = AETHER.urlSlot, $sty = AETHER.styleVal;
  var $str = AETHER.g.str;
  return [$obj([["tag", "div"], ["attrs", $obj([["id", "home"]])], ["style", $obj([["text-align", "center"], ["margin", "80px 0"]])], ["children", [$obj([["tag", "p"], ["attrs", $obj([["id", "logo"]])], ["style", $obj([])], ["children", [$obj([["tag", "span"], ["attrs", $obj([])], ["style", $obj([["font-size", "72px"], ["font-weight", "bold"], ["color", "#4285f4"]])], ["children", ["A"]]]), $obj([["tag", "span"], ["attrs", $obj([])], ["style", $obj([["font-size", "72px"], ["font-weight", "bold"], ["color", "#ea4335"]])], ["children", ["e"]]]), $obj([["tag", "span"], ["attrs", $obj([])], ["style", $obj([["font-size", "72px"], ["font-weight", "bold"], ["color", "#fbbc05"]])], ["children", ["t"]]]), $obj([["tag", "span"], ["attrs", $obj([])], ["style", $obj([["font-size", "72px"], ["font-weight", "bold"], ["color", "#4285f4"]])], ["children", ["h"]]]), $obj([["tag", "span"], ["attrs", $obj([])], ["style", $obj([["font-size", "72px"], ["font-weight", "bold"], ["color", "#34a853"]])], ["children", ["e"]]]), $obj([["tag", "span"], ["attrs", $obj([])], ["style", $obj([["font-size", "72px"], ["font-weight", "bold"], ["color", "#ea4335"]])], ["children", ["r"]]])]]]), $obj([["tag", "p"], ["attrs", $obj([["class", "tagline"]])], ["style", $obj([["color", "#4d5156"], ["letter-spacing", "4px"]])], ["children", ["只搜 Aether 生态"]]]), $obj([["tag", "div"], ["attrs", $obj([["class", "search-box"]])], ["style", $obj([["border", "1px solid #dfe1e5"], ["border-radius", "24px"], ["width", "420px"], ["margin", "28px auto"], ["padding", "12px"], ["color", "#70757a"]])], ["children", [$obj([["tag", "p"], ["attrs", $obj([])], ["style", $obj([])], ["children", ["本页为纯 HTML 模式(路由 script 省略,规格 16.7)"]]])]]]), $obj([["tag", "p"], ["attrs", $obj([])], ["style", $obj([])], ["children", [$obj([["tag", "a"], ["attrs", $obj([["class", "btn"], ["href", $escA($url("search.html?q=aether"))]])], ["style", $obj([["background", "#f2f3f4"], ["border-radius", "6px"], ["padding", "8px 16px"], ["margin", "4px"], ["color", "#3c4043"], ["text-decoration", "none"]])], ["children", ["Aether 搜索"]]]), $obj([["tag", "a"], ["attrs", $obj([["class", "btn"], ["href", $escA($url("docs/lang.html"))]])], ["style", $obj([["background", "#f2f3f4"], ["border-radius", "6px"], ["padding", "8px 16px"], ["margin", "4px"], ["color", "#3c4043"], ["text-decoration", "none"]])], ["children", ["手气不错"]]])]]]), $obj([["tag", "p"], ["attrs", $obj([])], ["style", $obj([["color", "#70757a"], ["margin", "80px 0 0 0"]])], ["children", ["Aether 搜索 · Powered by AetherJS · ", $obj([["tag", "a"], ["attrs", $obj([["href", $escA($url("about.html"))]])], ["style", $obj([])], ["children", ["关于"]]])]]])]]])];
}
